### PR TITLE
fix: add mapping of current POD IP to external IP

### PR DESCRIPTION
**Pull request by denis-tingaikin**
Signed-off-by: denis-tingajkin <denis.tingajkin@xored.com>

## Motivation

Related to https://github.com/networkservicemesh/sdk/issues/1015

### CODE REVIEW

**Comment by edwarnicke** [comment]
Why are we mapping Pod IP and not Node IP to external IP?  The forwarder should be running on the hostnetwork:true Node networking namespace...

**Comment by denis-tingaikin** [comment]
@edwarnicke yes, you're correct for mechanisms, but we also need to swap nsmgr-proxy IP to External IP on NSE registration to make NSE reachable over domain in case of public floating inter-domain scenario.

**Comment by edwarnicke** [comment]
Ah... so how are we getting an External IP for the nsmgr-proxy Pod?

**Comment by denis-tingaikin** [comment]
>Ah... so how are we getting an External IP for the nsmgr-proxy Pod?
In case of interdomain we are getting it via DNS.
In case of floating interdomain we can store it in floating registry entries in NSE registration: `url:${external-ip}:${nsmgr-proxy-port}`.

**Comment by edwarnicke** [comment]
I mean how is the nsmgr-proxy Pod figuring out what its externalIP is for purposes of registering it upstream to the registry.

**Comment by edwarnicke** [comment]
@denis-tingaikin Is the nsmgr-proxy also running in hostNetwork:true ?

**Comment by denis-tingaikin** [comment]
@edwarnicke Currently is not, and I think we may try to run in hostNetwork as an alternative of this patch

**Comment by edwarnicke** [comment]
@denis-tingaikin I'm very much in favor of *not* running nsmgr-proxy in hostNetwork:true.

I am a bit confused though because this PR seems to go looking for the ExternalIP for the Node, and is using that... which I would expect to be mapped to the Nodes InternalIP... and thus be delivered to hostNetwork:true

What am I misssing?

**Comment by denis-tingaikin** [comment]
> I am a bit confused though because this PR seems to go looking for the ExternalIP for the Node, and is using that... which I would expect to be mapped to the Nodes InternalIP... and thus be delivered to hostNetwork:true

> What am I misssing?

With this PR we'll add map current POD IP to External nodeName of the POD where cmd-map-ip-k8s is running. 

In this variant nsmgr-proxy will not have a `hostNetwork:true` and all   registrations to upstream floating-registry will have a ExternalIP of the node where nsmgr-proxy is running.

Note: To access to ${externaIP}:${port} we have this line in deployment: https://github.com/networkservicemesh/deployments-k8s/blob/main/apps/nsmgr-proxy/nsmgr-proxy.yaml#L24

So with this patch we'll not need to modify somehow cmd-nsmgr-proxy, but need to add nodeName ref in cmd-ip-map sidecar.

**Comment by edwarnicke** [comment]
Ah, got it, hostPort :)

**Comment by edwarnicke** [comment]
Happy to merge this... I wish we didn't need hostPort... but I don't know what other options we have to solve this problem.  So if something creative occurs to you, that's good... but otherwise, we can continue with this :)

**Pull request merged**
